### ISSUE TITLE
Facing issue while upgrading the starter kit from expo sdk 49 to sdk 51

### ISSUE THREAD

**Issue by sawankumar1012** [gluestack/expo-head-starter-kit#12]
i have tried reinstalling node modules , running npm expo fix , installing latest expo but still i am getting this issue 
<img width="1073" alt="Screenshot 2024-07-15 at 8 24 53 PM" src="https://github.com/user-attachments/assets/9c7ac7b4-d124-4ed0-b48e-9414ba7bd72a">

**Comment by devdudeio** [comment]
I encountered a similar issue. This repository uses Expo v49, but I installed the latest version (v51) on my phone. I can't open the app from this repo without upgrading to v51. Unfortunately, after upgrading Expo (npm install expo@latest), I get this error when starting via npm install:

```
johndoe@dev expo-head-starter-kit-main % npm start             

> expo-head-starter-kit@1.0.0 start
> expo start

Starting project at /Users/johndoe/Desktop/expo-head-starter-kit-main
Starting Metro Bundler
Error: Cannot find module '@expo/server/build/vendor/http'
Require stack:
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/metro/createServerRouteMiddleware.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/startAsync.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/index.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/bin/cli
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/expo/bin/cli
Error: Cannot find module '@expo/server/build/vendor/http'
Require stack:
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/metro/createServerRouteMiddleware.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/startAsync.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/src/start/index.js
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/build/bin/cli
- /Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/expo/bin/cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at createRouteHandlerMiddleware (/Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/src/start/server/metro/createServerRouteMiddleware.ts:44:5)
    at MetroBundlerDevServer.startImplementationAsync (/Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:688:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MetroBundlerDevServer.startAsync (/Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:159:18)
    at DevServerManager.startAsync (/Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/src/start/server/DevServerManager.ts:190:7)
    at startAsync (/Users/johndoe/Desktop/expo-head-starter-kit-main/node_modules/@expo/cli/src/start/startAsync.ts:105:3)
johndoe@dev expo-head-starter-kit-main % 
```

I used latest node lts iron (v20.15.1)
